# Generated by Django 4.2.7 on 2024-01-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('seats', models.PositiveIntegerField()),
                ('speed', models.FloatField()),
                ('carrier_company', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CrewMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('education', models.CharField(max_length=100)),
                ('experience', models.PositiveIntegerField()),
                ('passport_data', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('education', models.CharField(max_length=100)),
                ('experience', models.PositiveIntegerField()),
                ('passport_data', models.CharField(max_length=50)),
                ('is_airport_employee', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TransitStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport', models.CharField(max_length=50)),
                ('datetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=50)),
                ('distance', models.FloatField()),
                ('departure_airport', models.CharField(max_length=50)),
                ('destination_airport', models.CharField(max_length=50)),
                ('departure_datetime', models.DateTimeField()),
                ('arrival_datetime', models.DateTimeField()),
                ('sold_tickets', models.PositiveIntegerField()),
                ('transit_stops', models.ManyToManyField(blank=True, to='avia_app.transitstop')),
            ],
        ),
    ]